global using Microsoft.EntityFrameworkCore;
global using API.Entities;
global using FastEndpoints;
global using FastEndpoints.Swagger;
global using API.Contracts.Requests;
global using API.DbContexts;
global using API.Contracts.Responses;
global using API.Interfaces;
global using Microsoft.AspNetCore.Authorization;
global using API.Repositories;
global using AutoMapper;
global using System.Reflection;
global using IMapper = AutoMapper.IMapper;