global using HttpGetAttribute = FastEndpoints.HttpGetAttribute;
global using HttpPostAttribute = FastEndpoints.HttpPostAttribute;
global using HttpDeleteAttribute = FastEndpoints.HttpDeleteAttribute;
global using HttpPutAttribute = FastEndpoints.HttpPutAttribute;
global using IMapper = AutoMapper.IMapper;
global using Microsoft.EntityFrameworkCore;
global using API.Entities;
global using FastEndpoints;
global using FastEndpoints.Swagger;
global using API.Contracts.Requests;
global using API.DbContexts;
global using API.Contracts.Responses;
global using API.Interfaces;
global using Microsoft.AspNetCore.Authorization;
global using API.Repositories;
global using AutoMapper;
global using System.Reflection;
global using System.Text.Json;
global using API.Middleware;
global using FluentValidation;
global using Bogus;
global using API.Helpers;
global using AutoMapper.QueryableExtensions;
global using API.Extensions;
global using Microsoft.AspNetCore.Mvc;

