// <auto-generated />
using System;
using API.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace API.DbContexts.Migrations
{
    [DbContext(typeof(AmazonDbContext))]
    [Migration("20220826185841_SeededSomeProductsForTest")]
    partial class SeededSomeProductsForTest
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("API.Entities.ProductEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CountInStock")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountInStock = 11,
                            Created = new DateTime(2022, 8, 26, 18, 58, 41, 317, DateTimeKind.Utc).AddTicks(6198),
                            Name = "Laptop",
                            Price = 15000.5
                        },
                        new
                        {
                            Id = 2,
                            CountInStock = 123,
                            Created = new DateTime(2022, 8, 26, 18, 58, 41, 317, DateTimeKind.Utc).AddTicks(6201),
                            Name = "Mobile",
                            Price = 16000.5
                        },
                        new
                        {
                            Id = 3,
                            CountInStock = 43,
                            Created = new DateTime(2022, 8, 26, 18, 58, 41, 317, DateTimeKind.Utc).AddTicks(6202),
                            Name = "Moza",
                            Price = 13600.299999999999
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
